name: huariqueando
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc_pattern:
  rxdart:  


  cupertino_icons: ^0.1.2
  flutter_rating_bar: ^3.0.0
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
        - assets/images/
        - assets/icons/
